### ISSUE TITLE
clustering transcripts without segmentation

### ISSUE THREAD

**Issue by araksm** [kharchenkolab/Baysor#127]
Dear all,

Is it possible to get the output of 'clustering molecules' step without proceeding to the segmentation and creating polygons?

Thank you,
Araks

**Comment by VPetukhov** [comment]
Dear Araks,
It's possible if you run Baysor from Jupyter Notebooks in Julia. My bad, I haven't documented that option at all, as there were no request for that. But if you need it, I can draft a minimalistic notebook. Otherwise, you can set number of iterations to 1, so the segmentation would go stop very early.

**Comment by VPetukhov** [comment]
Yes, that's the one!
