### ISSUE TITLE
polygon cell geometry of Baysor segmentation vs Xenium

### ISSUE THREAD

**Issue by alipirani88** [kharchenkolab/Baysor#142]
Hi @VPetukhov 

I ran baysor with the following parameters:
`-m 50 -p --prior-segmentation-confidence 0.2 --scale-std 0.8 --scale 5 --save-polygons GeoJSON `

I see the cell boundaries are drawn like a polygon compare to xenium cell boundaries which seems to be more uniform. Is this expected from Baysor or did something went wrong during the segmentation?

I also see Baysor finding cells of unusual shapes and size in areas which Xenium segmentation is missing? I am not sure what to make ofit?

I would appreciate your thoughts on it. 

![Screenshot 2024-10-14 at 12 50 52 PM](https://github.com/user-attachments/assets/25431b36-a1c8-4a3d-84f5-44aaae233d78)

**Comment by alipirani88** [comment]
Also, the xenium sample is a multi tissue array - can baysor handle multi-tissue arrays ?

**Comment by VPetukhov** [comment]
Hi @alipirani88 ,

> I see the cell boundaries are drawn like a polygon compare to xenium cell boundaries which seems to be more uniform. Is this expected from Baysor or did something went wrong during the segmentation?

Yes, that's how Baysor usually outputs polygons. It's a variation of a concave hull algorithm.

> I also see Baysor finding cells of unusual shapes and size in areas which Xenium segmentation is missing? I am not sure what to make ofit?

Regions without prior segmentation are segmented de-novo. If you think that their size is too large, you can either manually provide `scale` parameter and set it to a smaller value, or you can filter the final segmentation results by cell area.

> Also, the xenium sample is a multi tissue array - can baysor handle multi-tissue arrays ?

Baysor assumes uniform cell sizes, which can be violated in multi-tissue arrays. *It can also be violated within the same tissue, but it that's the case see https://github.com/kharchenkolab/Baysor/issues/140*. That can be a reason why you see cells of unusual size. Also, in multi-tissue arrays NCV coloring would capture tissue differences instead of cell types. So, it would be better to split the data by tissue before Baysor.

**Comment by alipirani88** [comment]
Hi @VPetukhov,

What are your thoughts on cells that are called denovo by Baysor (not called by Xenium)? Specifically, in tissue regions where we dont see any nuclei in their H&E images?

**Comment by VPetukhov** [comment]
Hi @alipirani88 , Xenium stains are performed in 2D, so it's possible that there are some cells with nuclei being on a different z-plane than the stain. Some tissues may also have cells without nuclei (like red blood cells). It's also not uncommon that the DAPI/membrane signal doesn't perfectly match to molecule data. Though I don't know reasons for that, and I don't know whether this could happen with H&E.
