### ISSUE TITLE
Dataset Preview Issue

### ISSUE THREAD

**Issue by Yao-14** [kharchenkolab/Baysor#20]
Hello, when I used my own data for preview, I met the following error, please how to solve it

[19:02:47] Info: (2021-10-31) Run Baysor v0.5.0
[19:02:47] Info: Loading data...
[19:02:59] Info: Loaded 122333 transcripts
[19:02:59] Info: Estimating noise level
[19:03:09] Error: ArgumentError("Normal: the condition σ >= zero(σ) is not satisfied.")
|                 
|                 macro expansion at utils.jl:6 [inlined]
|                 #Normal#109 at normal.jl:37 [inlined]
|                 Normal at normal.jl:37 [inlined]
|                 (::Baysor.var"#132#133"{Vector{Int64}, Vector{Float64}, Matrix{Float64}})(i::Int64) at none:0
|                 iterate at generator.jl:47 [inlined]
|                 indexed_iterate at tuple.jl:89 [inlined]
|                 fit_noise_probabilities(edge_lengths::Vector{Float64}, adjacent_points::Vector{Vector{Int64}}, adjacent_weights::Vector{Vector{Float64}}; min_confidence::Nothing, max_iters::Int64, tol::Float64, verbose::Bool, progress::Nothing) at noise_estimation.jl:59
|                 fit_noise_probabilities at noise_estimation.jl:38 [inlined]
|                 append_confidence!(df_spatial::DataFrames.DataFrame, prior_assignment::Nothing; nn_id::Int64, prior_confidence::Float64) at noise_estimation.jl:110
|                 append_confidence! at noise_estimation.jl:104 [inlined]
|                 (::Baysor.var"#append_confidence!##kw")(::NamedTuple{(:nn_id,), Tuple{Int64}}, ::typeof(Baysor.append_confidence!), df_spatial::DataFrames.DataFrame) at noise_estimation.jl:104
|                 run_cli_preview(args::Vector{String}) at preview.jl:88
|                 run_cli(args::Vector{String}) at common.jl:122
|                 run_cli at common.jl:103 [inlined]
|                 julia_main at common.jl:139 [inlined]
|                 julia_main() at none:36
└ Baysor /home/vpetukhov/.julia/dev/Baysor/src/cli/common.jl:132

**Comment by VPetukhov** [comment]
Hello,
Looks like the noise detection algorithm converges to assigning all molecules to the same class, and we don't process this case properly. It should be easy to fix technically, but I'm not sure on what it means conceptually. What protocol is it? Is it 2D or 3D? And is there any chance you can share some data, so I could debug it?

**Comment by Yao-14** [comment]
Hello, this is the original test data we used. Our data is obtained through stereomics sequencing of BGI.
[Testdata.txt](https://github.com/kharchenkolab/Baysor/files/7472070/Testdata.txt)

**Comment by fengweimin-maker** [comment]
> Hello, this is the original test data we used. Our data is obtained through stereomics sequencing of BGI. [Testdata.txt](https://github.com/kharchenkolab/Baysor/files/7472070/Testdata.txt)

Hello, I also test the data of BGI, can we communicate with each other for the error?

**Comment by Yao-14** [comment]
> > Hello, this is the original test data we used. Our data is obtained through stereomics sequencing of BGI. [Testdata.txt](https://github.com/kharchenkolab/Baysor/files/7472070/Testdata.txt)
> 
> Hello, I also test the data of BGI, can we communicate with each other for the error?

Sure, How do you want to communicate?

**Comment by fengweimin-maker** [comment]
Hi，
    Did you use the tif image as input data ？And whether it came out error？
________________________________
发件人: Jiajun Yao ***@***.***>
发送时间: 2021年11月9日 3:04
收件人: kharchenkolab/Baysor ***@***.***>
抄送: 冯炜敏(Weimin Feng) ***@***.***>; Comment ***@***.***>
主题: Re: [kharchenkolab/Baysor] Dataset Preview Issue (Issue #20)


外部邮件/External Mail



Hello, this is the original test data we used. Our data is obtained through stereomics sequencing of BGI. Testdata.txt<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkharchenkolab%2FBaysor%2Ffiles%2F7472070%2FTestdata.txt&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479364382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PeAW3X2LICGmfw5X42fSyKgULRRH0MrTlvaIV6dD6AY%3D&reserved=0>

Hello, I also test the data of BGI, can we communicate with each other for the error?

Sure, How do you want to communicate?

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkharchenkolab%2FBaysor%2Fissues%2F20%23issuecomment-964042901&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479374365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BMrSVjRYKuMisziXRy%2BPRjz1XZo11C1YN6B7LsNEB5g%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAONV66CN7MVDTGQEQ3CTCHDULD52FANCNFSM5HCFF4AA&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479374365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4xZ3ugMIPbeIETgmBHZk30PCesvM7UlhJi2qxoy1mBU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479384361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KyfK%2BZIDmXzRvARNwSAvbkJgpaQUPPcNJW2vZDbXids%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479384361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OJw2tXElgvbQ%2Ffp7LASNzL59bAk%2FfS3sJo6cVv7VY2c%3D&reserved=0>.

**Comment by Yao-14** [comment]
Sorry, we don’t have a DAPI staining chart, so I just use the data matrix for testing.
| |
yjj_zj
|
|
***@***.***
|
签名由网易邮箱大师定制
On 11/9/2021 ***@***.***> wrote：

Hi，
Did you use the tif image as input data ？And whether it came out error？
________________________________
发件人: Jiajun Yao ***@***.***>
发送时间: 2021年11月9日 3:04
收件人: kharchenkolab/Baysor ***@***.***>
抄送: 冯炜敏(Weimin Feng) ***@***.***>; Comment ***@***.***>
主题: Re: [kharchenkolab/Baysor] Dataset Preview Issue (Issue #20)


外部邮件/External Mail



Hello, this is the original test data we used. Our data is obtained through stereomics sequencing of BGI. Testdata.txt<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkharchenkolab%2FBaysor%2Ffiles%2F7472070%2FTestdata.txt&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479364382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PeAW3X2LICGmfw5X42fSyKgULRRH0MrTlvaIV6dD6AY%3D&reserved=0>

Hello, I also test the data of BGI, can we communicate with each other for the error?

Sure, How do you want to communicate?

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkharchenkolab%2FBaysor%2Fissues%2F20%23issuecomment-964042901&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479374365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BMrSVjRYKuMisziXRy%2BPRjz1XZo11C1YN6B7LsNEB5g%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAONV66CN7MVDTGQEQ3CTCHDULD52FANCNFSM5HCFF4AA&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479374365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4xZ3ugMIPbeIETgmBHZk30PCesvM7UlhJi2qxoy1mBU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479384361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KyfK%2BZIDmXzRvARNwSAvbkJgpaQUPPcNJW2vZDbXids%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cfengweimin%40genomics.cn%7Cf022dc6df13142f3798208d9a370a496%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C0%7C637720526479384361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OJw2tXElgvbQ%2Ffp7LASNzL59bAk%2FfS3sJo6cVv7VY2c%3D&reserved=0>.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VPetukhov** [comment]
If it's still relevant, could you please try it on the latest version? If it still doesn't work, please reopen the issue.
