### ISSUE TITLE
Performance of Baysor

### ISSUE THREAD

**Issue by heihaizhengdong** [kharchenkolab/Baysor#4]
Hi Viktor,
It's an interesting project! I tried to run Baysor on my computer. However I’m new to Julia and thus struggled with many issues. 
In the examples file, it seems that you’ve tested it on STARmap dataset. So I’d appreciate it very much if you could also share the testing result of Baysor on STARmap to show more examples and performance of Baysor better. 
Thank you!

**Comment by VPetukhov** [comment]
Hi,
The STARmap protocol is actually the trickiest on our test. It still looks reasonable, but not as good as other protocols. [Here](http://pklab.med.harvard.edu/viktor/baysor/starmap/star_map_vis_1020.zip) are the results of the segmentation. Mainly it happens because the published data has one weird artefact: molecules are not uniformly mixed within a cell. Instead, all molecules of the same gene seat very close to each other, here is an example:
![Screenshot_20200914_202530](https://user-images.githubusercontent.com/6990194/93123506-84324300-f6c8-11ea-969a-54a5ba21e1d2.png).

So, if your data don't have such problem, results should be much better. We'll have a discussion of it in the paper.

**Comment by heihaizhengdong** [comment]
Thanks! That's very helpful!
