### ISSUE TITLE
Issues on execute baysor:latest in docker.

### ISSUE THREAD

**Issue by SeokJinYeo** [kharchenkolab/Baysor#53]
I am trying to use baysor with docker. I had no problem with vpetukhov/baysor:master. I could run baysor. 
However, when I try to use vpetukhov/baysor:latest version, there was some issue.
When I run baysor, the error happened.
```
baysor
ERROR: Unable to find compatible target in system image.
```
How can I use baysor:latest version? Can I learn the reason of this error?
Any help would be very appreciated.

I'm using windows(x64).

**Comment by VPetukhov** [comment]
Hi @SeokJinYeo ,
The reason is that compiled julia system images use certain CPU flags, which may not be available in your CPU. I tried to set them as general as reasonably possible, but disregarding all CPU optimization would lead to a huge drop in performance, so I can't make it 100% general. If the problem persists with the new Docker image (v0.6.0), I suggest building docker on your own (clone the repo, go to the directory and run `docker build .`). It would produce an equivalent docker image, but would guarantee that the CPU optimizations are compatible with your machine.
